# Generated by Django 6.0.3 on 2026-04-10 05:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ShortLinkModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uid',
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name='UUID',
                    ),
                ),
                (
                    'original_url',
                    models.URLField(
                        max_length=500, verbose_name='original URL',
                    ),
                ),
                (
                    'short_code',
                    models.CharField(
                        unique=True, verbose_name='short url code',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created date',
                    ),
                ),
                (
                    'clicks',
                    models.PositiveIntegerField(
                        default=0, verbose_name='clicks count',
                    ),
                ),
            ],
            options={
                'verbose_name': 'short link',
                'verbose_name_plural': 'short links',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['short_code'],
                        name='urlshortene_short_c_d00fe0_idx',
                    ),
                    models.Index(
                        fields=['-created_at'],
                        name='urlshortene_created_c436ba_idx',
                    ),
                ],
            },
        ),
    ]
