# Generated by Django 6.0.3 on 2026-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkmodel',
            name='short_code',
            field=models.CharField(
                max_length=8,
                unique=True,
                verbose_name='short url code',
            ),
        ),
    ]
